/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort.h"
#include "IfxPort_PinMap.h"

#include "IfxStm.h"
#include "IfxCpu_Irq.h"

#include "IfxScuEru.h"

#define SCLK     IfxPort_P00_0
#define RCLK     IfxPort_P00_1
#define DIO      IfxPort_P00_2

IfxCpu_syncEvent cpuSyncEvent = 0;

IFX_INTERRUPT(SW1_ISR, 0, 0x10u);
IFX_INTERRUPT(SW2_ISR, 0, 0x20u);

volatile uint16 g_counter = 0;   // 0~9999
volatile uint8  g_state = 1;     // 1: 동작, 0: 정지

void SW1_ISR(void)
{
    IfxScuEru_clearEventFlag(IfxScuEru_InputChannel_3);
    g_state ^= 1;
}

void SW2_ISR(void)
{
    IfxScuEru_clearEventFlag(IfxScuEru_InputChannel_2);
    g_counter = 0;
}

void initGPIO(void)
{
    IfxPort_setPinModeOutput(SCLK.port, SCLK.pinIndex,
                             IfxPort_OutputMode_pushPull,
                             IfxPort_OutputIdx_general);

    IfxPort_setPinModeOutput(RCLK.port, RCLK.pinIndex,
                             IfxPort_OutputMode_pushPull,
                             IfxPort_OutputIdx_general);

    IfxPort_setPinModeOutput(DIO.port, DIO.pinIndex,
                             IfxPort_OutputMode_pushPull,
                             IfxPort_OutputIdx_general);

    IfxPort_setPinLow(SCLK.port, SCLK.pinIndex);
    IfxPort_setPinLow(RCLK.port, RCLK.pinIndex);
    IfxPort_setPinLow(DIO.port, DIO.pinIndex);
}

uint8 _LED_0F[10] = {0xC0, 0xf9, 0xa4, 0xb0, 0x99, 0x92, 0x82, 0xf8, 0x80, 0x90};


void send(uint8 X) {
    for(int i=8;i>=1;i--) {
        if(X & 0x80) {
            IfxPort_setPinHigh(DIO.port, DIO.pinIndex);
        } else {
            IfxPort_setPinLow(DIO.port, DIO.pinIndex);
        }
        X <<= 1;
        IfxPort_setPinLow(SCLK.port, SCLK.pinIndex);
        IfxPort_setPinHigh(SCLK.port, SCLK.pinIndex);
    }
}

void send_port(uint8 X, uint8 port) {
    send(X);
    send(port);
    IfxPort_setPinLow(RCLK.port, RCLK.pinIndex);
    IfxPort_setPinHigh(RCLK.port, RCLK.pinIndex);
}

void initERU(void)
{
    /* -------------------- SW1 : P02.0 -------------------- */

    IfxPort_setPinModeInput(IfxPort_P02_0.port,
                            IfxPort_P02_0.pinIndex,
                            IfxPort_InputMode_pullUp);

    // Input Channel 3 선택
    IfxScuEru_selectExternalInput(IfxScuEru_InputChannel_3,
                                  IfxScuEru_ExternalInputSelection_2);

    IfxScuEru_enableFallingEdgeDetection(IfxScuEru_InputChannel_3);
    IfxScuEru_disableRisingEdgeDetection(IfxScuEru_InputChannel_3);

    IfxScuEru_enableTriggerPulse(IfxScuEru_InputChannel_3);

    // Output Channel 1에 연결
    IfxScuEru_connectTrigger(IfxScuEru_InputChannel_3,
                             IfxScuEru_InputNodePointer_1);

    IfxScuEru_setInterruptGatingPattern(
        IfxScuEru_OutputChannel_1,
        IfxScuEru_InterruptGatingPattern_alwaysActive);

    IfxScuEru_setFlagPatternDetection(
        IfxScuEru_OutputChannel_1,
        IfxScuEru_InputChannel_3,
        TRUE);

    IfxScuEru_clearEventFlag(IfxScuEru_InputChannel_3);

    // ERU1 → Priority 0x10
    IfxSrc_init(&SRC_SCU_SCU_ERU1, IfxSrc_Tos_cpu0, 0x10u);
    IfxSrc_enable(&SRC_SCU_SCU_ERU1);


    /* -------------------- SW2 : P02.1 -------------------- */

    IfxPort_setPinModeInput(IfxPort_P02_1.port,
                            IfxPort_P02_1.pinIndex,
                            IfxPort_InputMode_pullUp);

    // Input Channel 2 선택
    IfxScuEru_selectExternalInput(IfxScuEru_InputChannel_2,
                                  IfxScuEru_ExternalInputSelection_1);

    IfxScuEru_enableFallingEdgeDetection(IfxScuEru_InputChannel_2);
    IfxScuEru_disableRisingEdgeDetection(IfxScuEru_InputChannel_2);

    IfxScuEru_enableTriggerPulse(IfxScuEru_InputChannel_2);

    // Output Channel 2에 연결
    IfxScuEru_connectTrigger(IfxScuEru_InputChannel_2,
                             IfxScuEru_InputNodePointer_2);

    IfxScuEru_setInterruptGatingPattern(
        IfxScuEru_OutputChannel_2,
        IfxScuEru_InterruptGatingPattern_alwaysActive);

    IfxScuEru_setFlagPatternDetection(
        IfxScuEru_OutputChannel_2,
        IfxScuEru_InputChannel_2,
        TRUE);

    IfxScuEru_clearEventFlag(IfxScuEru_InputChannel_2);

    // ERU2 → Priority 0x20
    IfxSrc_init(&SRC_SCU_SCU_ERU2, IfxSrc_Tos_cpu0, 0x20u);
    IfxSrc_enable(&SRC_SCU_SCU_ERU2);
}


void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    initGPIO();
    initERU();
        
    while(1)
    {
        int n1, n2, n3, n4;

        /* -------- 숫자 증가 -------- */
        if(g_state)
        {
            g_counter++;

            if(g_counter > 9999)
                g_counter = 0;
        }

        /* -------- 자리 분리 -------- */
        n1 = g_counter % 10;
        n2 = (g_counter / 10) % 10;
        n3 = (g_counter / 100) % 10;
        n4 = (g_counter / 1000) % 10;

        /* -------- FND 스캔 -------- */
        for(int i=0;i<200;i++)
        {
            send_port(_LED_0F[n1], 0x1);
            send_port(_LED_0F[n2], 0x2);
            send_port(_LED_0F[n3], 0x4);
            send_port(_LED_0F[n4], 0x8);
        }
    }
}
